# Generated by Django 4.1.1 on 2023-01-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('levels', '0001_initial'),
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regNumber', models.CharField(max_length=15, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Barr.', 'Barr.'), ('Prof.', 'Prof.')], max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('yearOfEntry', models.DateField()),
                ('yearOfGraduation', models.DateField()),
                ('username', models.EmailField(max_length=100, unique=True)),
                ('courses', models.ManyToManyField(blank=True, to='subjects.subject')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
    ]
