# Generated by Django 4.1.1 on 2023-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
