# Generated by Django 4.1.1 on 2023-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('title', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
