# Generated by Django 4.1.1 on 2023-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_remove_lecturer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='username',
            field=models.EmailField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
