# Generated by Django 4.1.7 on 2023-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_lecturer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
